# Generated by Django 4.2.6 on 2023-11-16 16:48

import apps.Mercancia.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anillo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('precio_unidad', models.FloatField(blank=True, default=0, null=True)),
                ('pureza', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('size', models.CharField(blank=True, max_length=5, null=True)),
                ('peso_neto', models.FloatField(blank=True, default=0, null=True)),
                ('genero_usuario', models.CharField(blank=True, choices=[('fa fa-venus-mars', 'Unisex'), ('fa fa-venus', 'Female'), ('fa fa-mars', 'Male')], max_length=17, null=True)),
                ('lugar_de_uso', models.CharField(blank=True, choices=[('mano', 'Mano'), ('pie', 'Pie')], max_length=4, null=True)),
                ('cantidad', models.CharField(blank=True, choices=[('simple', 'Simple'), ('pareja', 'Pareja')], max_length=6, null=True)),
                ('tipo_anillo', models.CharField(blank=True, choices=[('compromiso', 'Compromiso'), ('matrimonio', 'Matrimonio'), ('normal', 'Normal')], max_length=10, null=True)),
                ('photo', models.ImageField(default='none', upload_to=apps.Mercancia.models.anillo_photo_directory)),
                ('photo2', models.ImageField(default='none', upload_to=apps.Mercancia.models.anillo_photo_directory)),
                ('photo3', models.ImageField(default='none', upload_to=apps.Mercancia.models.anillo_photo_directory)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Arete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('precio_unidad', models.FloatField(blank=True, default=0, null=True)),
                ('pureza', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('size', models.CharField(blank=True, max_length=5, null=True)),
                ('peso_neto', models.FloatField(blank=True, default=0, null=True)),
                ('genero_usuario', models.CharField(blank=True, choices=[('fa fa-venus-mars', 'Unisex'), ('fa fa-venus', 'Female'), ('fa fa-mars', 'Male')], max_length=17, null=True)),
                ('unidades', models.CharField(blank=True, choices=[('solo', 'Solo'), ('pareja', 'Pareja')], max_length=6, null=True)),
                ('photo', models.ImageField(default='none', upload_to=apps.Mercancia.models.arete_photo_directory)),
                ('photo2', models.ImageField(default='none', upload_to=apps.Mercancia.models.arete_photo_directory)),
                ('photo3', models.ImageField(default='none', upload_to=apps.Mercancia.models.arete_photo_directory)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Brazalete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('precio_unidad', models.FloatField(blank=True, default=0, null=True)),
                ('pureza', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('size', models.CharField(blank=True, max_length=5, null=True)),
                ('peso_neto', models.FloatField(blank=True, default=0, null=True)),
                ('genero_usuario', models.CharField(blank=True, choices=[('fa fa-venus-mars', 'Unisex'), ('fa fa-venus', 'Female'), ('fa fa-mars', 'Male')], max_length=17, null=True)),
                ('photo', models.ImageField(default='none', upload_to=apps.Mercancia.models.brazalete_photo_directory)),
                ('photo2', models.ImageField(default='none', upload_to=apps.Mercancia.models.brazalete_photo_directory)),
                ('photo3', models.ImageField(default='none', upload_to=apps.Mercancia.models.brazalete_photo_directory)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cadena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('precio_unidad', models.FloatField(blank=True, default=0, null=True)),
                ('pureza', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('size', models.CharField(blank=True, max_length=5, null=True)),
                ('peso_neto', models.FloatField(blank=True, default=0, null=True)),
                ('genero_usuario', models.CharField(blank=True, choices=[('fa fa-venus-mars', 'Unisex'), ('fa fa-venus', 'Female'), ('fa fa-mars', 'Male')], max_length=17, null=True)),
                ('photo', models.ImageField(default='none', upload_to=apps.Mercancia.models.cadena_photo_directory)),
                ('photo2', models.ImageField(default='none', upload_to=apps.Mercancia.models.cadena_photo_directory)),
                ('photo3', models.ImageField(default='none', upload_to=apps.Mercancia.models.cadena_photo_directory)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dije',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('precio_unidad', models.FloatField(blank=True, default=0, null=True)),
                ('pureza', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('size', models.CharField(blank=True, max_length=5, null=True)),
                ('peso_neto', models.FloatField(blank=True, default=0, null=True)),
                ('genero_usuario', models.CharField(blank=True, choices=[('fa fa-venus-mars', 'Unisex'), ('fa fa-venus', 'Female'), ('fa fa-mars', 'Male')], max_length=17, null=True)),
                ('tipo_dije', models.CharField(blank=True, choices=[('animales', 'Animales'), ('flores', 'Flores'), ('formas', 'Formas'), ('otros', 'Otros')], max_length=10, null=True)),
                ('photo', models.ImageField(default='none', upload_to=apps.Mercancia.models.dije_photo_directory)),
                ('photo2', models.ImageField(default='none', upload_to=apps.Mercancia.models.dije_photo_directory)),
                ('photo3', models.ImageField(default='none', upload_to=apps.Mercancia.models.dije_photo_directory)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pircing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('precio_unidad', models.FloatField(blank=True, default=0, null=True)),
                ('pureza', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('size', models.CharField(blank=True, max_length=5, null=True)),
                ('peso_neto', models.FloatField(blank=True, default=0, null=True)),
                ('genero_usuario', models.CharField(blank=True, choices=[('fa fa-venus-mars', 'Unisex'), ('fa fa-venus', 'Female'), ('fa fa-mars', 'Male')], max_length=17, null=True)),
                ('lugar_de_uso', models.CharField(blank=True, choices=[('oreja', 'Oreja'), ('nariz', 'Nariz'), ('boca', 'Boca'), ('ombligo', 'Ombligo'), ('otro', 'Otro')], max_length=7, null=True)),
                ('photo', models.ImageField(default='none', upload_to=apps.Mercancia.models.pircing_photo_directory)),
                ('photo2', models.ImageField(default='none', upload_to=apps.Mercancia.models.pircing_photo_directory)),
                ('photo3', models.ImageField(default='none', upload_to=apps.Mercancia.models.pircing_photo_directory)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tobillera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('precio_unidad', models.FloatField(blank=True, default=0, null=True)),
                ('pureza', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('size', models.CharField(blank=True, max_length=5, null=True)),
                ('peso_neto', models.FloatField(blank=True, default=0, null=True)),
                ('genero_usuario', models.CharField(blank=True, choices=[('fa fa-venus-mars', 'Unisex'), ('fa fa-venus', 'Female'), ('fa fa-mars', 'Male')], max_length=17, null=True)),
                ('photo', models.ImageField(default='none', upload_to=apps.Mercancia.models.tobillera_photo_directory)),
                ('photo2', models.ImageField(default='none', upload_to=apps.Mercancia.models.tobillera_photo_directory)),
                ('photo3', models.ImageField(default='none', upload_to=apps.Mercancia.models.tobillera_photo_directory)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
