# Generated by Django 4.2.6 on 2023-12-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mercancia', '0004_alter_anillo_peso_neto_alter_anillo_pureza_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MercanciaObjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='anillo',
            name='estado',
            field=models.CharField(choices=[('privado', 'Privado'), ('publico', 'Publico')], default='privado', max_length=8),
        ),
        migrations.AddField(
            model_name='arete',
            name='estado',
            field=models.CharField(choices=[('privado', 'Privado'), ('publico', 'Publico')], default='privado', max_length=8),
        ),
        migrations.AddField(
            model_name='brazalete',
            name='estado',
            field=models.CharField(choices=[('privado', 'Privado'), ('publico', 'Publico')], default='privado', max_length=8),
        ),
        migrations.AddField(
            model_name='cadena',
            name='estado',
            field=models.CharField(choices=[('privado', 'Privado'), ('publico', 'Publico')], default='privado', max_length=8),
        ),
        migrations.AddField(
            model_name='dije',
            name='estado',
            field=models.CharField(choices=[('privado', 'Privado'), ('publico', 'Publico')], default='privado', max_length=8),
        ),
        migrations.AddField(
            model_name='pircing',
            name='estado',
            field=models.CharField(choices=[('privado', 'Privado'), ('publico', 'Publico')], default='privado', max_length=8),
        ),
        migrations.AddField(
            model_name='tobillera',
            name='estado',
            field=models.CharField(choices=[('privado', 'Privado'), ('publico', 'Publico')], default='privado', max_length=8),
        ),
    ]
