# Generated by Django 4.2.6 on 2023-12-05 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mercancia', '0005_mercanciaobjects_anillo_estado_arete_estado_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MercanciaObjects',
        ),
    ]
