# Generated by Django 4.2.6 on 2024-01-01 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mercancia', '0006_delete_mercanciaobjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anillo',
            name='cantidad',
            field=models.CharField(blank=True, choices=[('simple', 'Simple'), ('pareja', 'Pareja')], default='simple', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='anillo',
            name='genero_usuario',
            field=models.CharField(blank=True, choices=[('unisex', 'Unisex'), ('female', 'Female'), ('male', 'Male')], default='unisex', max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='anillo',
            name='lugar_de_uso',
            field=models.CharField(blank=True, choices=[('mano', 'Mano'), ('pie', 'Pie')], default='mano', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='anillo',
            name='name',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='anillo',
            name='tipo_anillo',
            field=models.CharField(blank=True, choices=[('compromiso', 'Compromiso'), ('matrimonio', 'Matrimonio'), ('normal', 'Normal')], default='normal', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='arete',
            name='genero_usuario',
            field=models.CharField(blank=True, choices=[('unisex', 'Unisex'), ('female', 'Female'), ('male', 'Male')], default='unisex', max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='arete',
            name='name',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='arete',
            name='unidades',
            field=models.CharField(blank=True, choices=[('solo', 'Solo'), ('pareja', 'Pareja')], default='pareja', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='brazalete',
            name='genero_usuario',
            field=models.CharField(blank=True, choices=[('unisex', 'Unisex'), ('female', 'Female'), ('male', 'Male')], default='unisex', max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='brazalete',
            name='name',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cadena',
            name='genero_usuario',
            field=models.CharField(blank=True, choices=[('unisex', 'Unisex'), ('female', 'Female'), ('male', 'Male')], default='unisex', max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='cadena',
            name='name',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='dije',
            name='genero_usuario',
            field=models.CharField(blank=True, choices=[('unisex', 'Unisex'), ('female', 'Female'), ('male', 'Male')], default='unisex', max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='dije',
            name='name',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='dije',
            name='tipo_dije',
            field=models.CharField(blank=True, choices=[('animales', 'Animales'), ('flores', 'Flores'), ('formas', 'Formas'), ('otros', 'Otros')], default='otros', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pircing',
            name='genero_usuario',
            field=models.CharField(blank=True, choices=[('unisex', 'Unisex'), ('female', 'Female'), ('male', 'Male')], default='unisex', max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='pircing',
            name='lugar_de_uso',
            field=models.CharField(blank=True, choices=[('oreja', 'Oreja'), ('nariz', 'Nariz'), ('boca', 'Boca'), ('ombligo', 'Ombligo'), ('otro', 'Otro')], default='otro', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='pircing',
            name='name',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tobillera',
            name='genero_usuario',
            field=models.CharField(blank=True, choices=[('unisex', 'Unisex'), ('female', 'Female'), ('male', 'Male')], default='unisex', max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='tobillera',
            name='name',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
